test: &test
  adapter: mysql2
  database: AARM_test
  encoding: utf8
  host: 127.0.0.1
  username: AARM
  password: AARM
  pool: 5
  socket: /var/run/mysqld/mysqld.sock

cucumber:
  <<: *test

development:
  adapter: mysql2
  database: AARM_development
  encoding: utf8
  host: 127.0.0.1
  username: AARM
  password: AARM
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
